--- # This file is used by Ansible to dynamically generate an inventory from Terraform-managed resources.
# Use the Terraform inventory plugin for Ansible
plugin: community.general.terraform
options:
  # Path to your Terraform project (relative to this file)
  project_path: ..
  # Only include resources that are currently present
  state: present
  # Refresh the Terraform state before generating inventory
  refresh: yes
  compose:
    # Set the Ansible host IP for each VM (prefer gateway IP, fallback to client IP)
    ansible_host: attributes.gateway_internet_ips | default(attributes.client_ips)
    # Set the role variable for each host (default to 'client' if not specified)
    role: attributes.role | default('client')

# Example groupings (customize as needed)
groups:
  # Group hosts with role 'gateway' into the 'gateway' group
  gateway: "attributes.role == 'gateway'"
  # Group hosts with role 'client' into the 'client' group
  client: "attributes.role == 'client'"
